version: "3"
services:
  frontend:
    image: frontend
    restart: always
    container_name: frontend
    build: app/frontend
    init: true
    env_file:
      - ./.env
    ports:
      - 80:3000
    volumes:
      - front:/home/frontend

  backend:
    image: backend
    restart: always
    container_name: backend
    build: app/backend
    init: true
    env_file:
      - ./.env
    ports:
      - 81:80
    volumes:
      - back:/home/backend


  postgresql:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/Desktop/42seoul/db/
  front:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/Desktop/42Seoul/frontend
  back:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/Desktop/42seoul/backend/