version: "3"
services:
  frontend:
    image: frontend
    restart: always
    container_name: frontend
    build: app/frontend
    init: true
    env_file:
      - ./.env
    ports:
      - 80:3000
    volumes:
      - front:/home/frontend

  backend:
    image: backend
    restart: always
    container_name: backend
    build: app/backend
    init: true
    env_file:
      - ./.env
    ports:
      - 81:80
    volumes:
      - back:/home/backend


  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:${POSTGRES_PORT}
    user: ${POSTGRES_USERNAME}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USERNAME", "-d", "$POSTGRES_DB" ]
      interval: 5m
      timeout: 5s
      retries: 5


volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/app/db
  front:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/app/frontend
  back:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/app/backend