version: "3"
services:
  frontend:
    image: frontend
    container_name: frontend
    build: app/frontend
    depends_on:
      - backend
    restart: always
    init: true
    env_file:
      - ./.env
    ports:
      - 80:3000
    volumes:
      - front:/home/frontend
    # networks:
    #   mynetwork:

  backend:
    image: backend
    container_name: backend
    build: app/backend
    depends_on:
      - postgresql
    restart: always
    init: true
    env_file:
      - ./.env
    ports:
      - 81:80
    volumes:
      - back:/home/backend
    # networks:
    #   mynetwork:
    #     ipv4_address: 172.26.0.10

  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    init: true
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:${POSTGRES_PORT}
    user: ${POSTGRES_USERNAME}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USERNAME", "-d", "$POSTGRES_DB" ]
      interval: 5m
      timeout: 5s
      retries: 5
    # networks:
    #   mynetwork:

volumes:
  db:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
      # device: ${HOME}/app/db
  front:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/app/frontend
  back:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/app/backend

# networks:
#   mynetwork:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.26.0.0/16
